# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52bb061151173ff84f3a563d0bc4522102874f4244150afb83a9bb600511bb065e7a31472b9a8b863e5d818342520a7e4c39c76c7dfbe766a65a31eaef192bcd

test:
  secret_key_base: 614d57f22219c1f3e04a3bb6f000d5ba298d69a6af2c1f43c5515f62134594a557cf7b3ada926ee81cba3c1d046bf54e17e5ddf86cfd69564faccf154cfc2b84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
